### ISSUE TITLE
How to set the app to measure distance to plier also?

### ISSUE THREAD

**Issue by jasirjasir** [MrLacuqer/hj-object-detect#3]
In my knowledge currently app will detect distance only to hammer. Where to set the Plier information to get distance form camera link

**Comment by hj26-park** [comment]
Would you changed the targetObjectList[0] 'hammer' to 'plier' in [YoloObjectDetector.cpp](https://github.com/MrLacquer/hj-object-detect/blob/f586e901233c126dc44de11ef79cfc08571545f9/copy_paste_files/YoloObjectDetector.cpp#L34) ? line 34.
```
std::string targetObjectList[] = {"hammer", "plier"}; 
↓ changed to
std::string targetObjectList[] = {"plier"};
```
