### ISSUE TITLE
How to use own objects

### ISSUE THREAD

**Issue by thejeshk** [MrLacuqer/hj-object-detect#5]
Hi 

Nice work!! 

Could you please help me with detecting own objects ?

**Comment by hj26-park** [comment]
If you want to detect your own object, 
first, do it new YOLO training. that is, you can easily find Google it.

and then, changed the name in your own object in  [YoloObjectDetector.cpp](https://github.com/MrLacquer/hj-object-detect/blob/f586e901233c126dc44de11ef79cfc08571545f9/copy_paste_files/YoloObjectDetector.cpp#L34) 
check up this [issue](https://github.com/MrLacquer/hj-object-detect/issues/3#issue-641797972)

**Comment by thejeshk** [comment]
> If you want to detect your own object,
> first, do it new YOLO training. that is, you can easily find Google it.
> 
> and then, changed the name in your own object in [YoloObjectDetector.cpp](https://github.com/MrLacquer/hj-object-detect/blob/f586e901233c126dc44de11ef79cfc08571545f9/copy_paste_files/YoloObjectDetector.cpp#L34)
> check up this [issue](https://github.com/MrLacquer/hj-object-detect/issues/3#issue-641797972)

Thank you @MrLacquer 

I have to use virtual camera node instead of Intel real sense camera (which is coming from AirSim) 

So I just have to modify in launch file right?

**Comment by hj26-park** [comment]
Yeahh...? Maybe? I'm not sure.
If your virtual camera's topic types are the same as realsense, then it will be work.
